version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./../../../src/main/resources/ddl/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
      - ./testdata/insert-testdata.sql:/docker-entrypoint-initdb.d/insert-testdata.sql
