#Use your favourite clients like Postman to run the following requests
# This file is probably runnable if you have a Intellij Ultimate version

POST http://localhost:8080/api/users
Content-Type: application-json

{
  "userId": "47665ac3-e04c-40b3-90ff-735bab2e87a3",
  "firstName": "Bengt",
  "lastName": "Bergström",
  "dateOfBirth": "19630304",
  "gender": null,
  "unokod": "BB0304",
  "phone": null,
  "email": "BB@Test.com",
  "kommun": null,
  "place": null,
  "payingCharges": false,
  "caseManager": "Ordnings Vakt",
  "understandsSwedish": false,
  "languagesKnown": null,
  "reasonsForHomelessness": null,
  "goals": null,
  "commentsAndRemarks": null,
  "reservationId": null,
  "flagged": false
}

###
# Get ALL Users
GET http://localhost:8080/api/users