name: Create noQ domain certs

# Controls when the workflow will run
on:
  # schedule:
  #   - cron:  '0 5 */31 * *'
  workflow_dispatch:
  push:
    branches:
      - "jonsing/domain-setup"

jobs:
  create_cert:
    # env:
      # DOMAIN: ${{ secrets.DOMAIN }}  
    name: Cert dev.noq.nu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Install certbot
        run: |
          echo "Install dependencies"
          sudo apt install -y certbot openssl

      - name: Generate cert
        run: |
          sudo certbot certonly -d dev.noq.nu -m martin@jonsing.se --config-dir . --cert-path . --manual --preferred-challenges=dns --non-interactive --agree-tos
