name: noQ - PR Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:

  # Verify build of frontend
  build-frontend:
    name: 'Validate frontend build'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: frontend/react
        run: npm install

      - name: Build frontend
        working-directory: frontend/react
        run: npm run build

  # Verify build of backend
  build-backend:
    name: 'Validate backend build'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        working-directory: noq-backend/
        run: mvn -B package --file pom.xml -e